version: 0.2

phases:
  install:
    runtime-versions:
      python: 3.9
    commands:
      - echo Instalando dependencias...
      - pip install --upgrade pip
  pre_build:
    commands:
      - echo Fase de pre-construcción...
      # Eliminar cualquier archivo ZIP previo si existe
      - rm -f deployment.zip
      - mkdir -p package
  build:
    commands:
      - echo Construcción iniciada en `date`
      # Instalar las dependencias en el directorio 'package'
      - pip install -r requirements.txt -t package/
      # Copiar todos los archivos al directorio 'package', excepto el directorio 'package' y el archivo ZIP
      - rsync -av --exclude='package/' --exclude='deployment.zip' . package/
      # Crear el archivo ZIP fuera del directorio actual con un nombre diferente
      - cd package
      - zip -r ../deployment.zip ./*
  post_build:
    commands:
      - echo Construcción completada en `date`
artifacts:
  files:
    - deployment.zip
