version: 0.2

phases:
  install:
    runtime-versions:
      python: 3.9
    commands:
      - echo Instalando dependencias...
      - pip install --upgrade pip
  pre_build:
    commands:
      - echo Fase de pre-construcción...
      # Eliminar cualquier archivo ZIP previo si existe
      - rm -f OpenAIGenerator.zip
      - mkdir -p package
  build:
    commands:
      - echo Construcción iniciada en `date`
      # Instalar las dependencias en el directorio 'package'
      - pip install -r requirements.txt -t package/
      # Copiar todos los archivos del proyecto en el directorio 'package'
      - cp -r * package/
      # Comprimir todos los archivos en el archivo ZIP
      - cd package
      - zip -r ../OpenAIGenerator.zip ./*
  post_build:
    commands:
      - echo Construcción completada en `date`
artifacts:
  files:
    - OpenAIGenerator.zip
