version: 0.2

phases:
  install:
    runtime-versions:
      python: 3.9
    commands:
      - echo Instalando dependencias...
      - pip install --upgrade pip
      - pip install -r requirements.txt -t .
  pre_build:
    commands:
      - echo Fase de pre-construcción...
  build:
    commands:
      - echo Construcción iniciada en `date`
      - zip -r OpenAIGenerator.zip .
  post_build:
    commands:
      - echo Construcción completada en `date`
artifacts:
  files:
    - OpenAIGenerator.zip
