version: 0.2

phases:
  install:
    runtime-versions:
      python: 3.9
    commands:
      - echo Instalando dependencias...
      - pip install --upgrade pip
  pre_build:
    commands:
      - echo Fase de pre-construcción...
      # Eliminar cualquier archivo ZIP previo si existe
      - rm -f OpenAIGenerator.zip
      - mkdir -p package
  build:
    commands:
      - echo Construcción iniciada en `date`
      # Instalar las dependencias en el directorio 'package'
      - pip install -r requirements.txt -t package/
      # Copiar todos los archivos excepto el directorio 'package' y el archivo ZIP anterior
      - cp -r $(ls | grep -v package | grep -v OpenAIGenerator.zip) package/
      # Navegar a 'package' y crear el archivo ZIP en el directorio superior
      - cd package
      - zip -r ../OpenAIGenerator.zip ./*
  post_build:
    commands:
      - echo Construcción completada en `date`
artifacts:
  files:
    - OpenAIGenerator.zip
