version: 0.2

phases:
  install:
    runtime-versions:
      python: 3.9
    commands:
      - echo Instalando dependencias...
      - pip install --upgrade pip
  pre_build:
    commands:
      - echo Fase de pre-construcción...
      # Eliminar cualquier archivo ZIP previo si existe
      - rm -f OpenAIGenerator.zip
  build:
    commands:
      - echo Construcción iniciada en `date`
      - cd OpenAIGenerator
      # Comprimir todos los archivos y subdirectorios en el archivo ZIP
      - zip -r OpenAIGenerator.zip ./*
  post_build:
    commands:
      - echo Construcción completada en `date`
artifacts:
  files:
    - OpenAIGenerator.zip
