version: 0.2

phases:
  install:
    runtime-versions:
      python: 3.9
    commands:
      - echo Installing dependencies...
      - pip install --upgrade pip
      - pip install -r requirements.txt -t .
  pre_build:
    commands:
      - echo Pre-build phase...
      # Eliminar el archivo ZIP anterior si existe
      - rm -f OpenAIGenerator.zip
  build:
    commands:
      - echo Build started on `date`
      # Empaquetar el proyecto excluyendo cualquier archivo anterior ZIP
      - zip -r OpenAIGenerator.zip ./*
  post_build:
    commands:
      - echo Build completed on `date`
artifacts:
  files:
    - OpenAIGenerator.zip
